name: shelf_estudo
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.5.2
  orm: ^2.3.0
  shelf_hotreload: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.1
